# PL Trainer doc
# https://pytorch-lightning.readthedocs.io/en/stable/common/trainer.html

# reproducibility
deterministic: False
random_seed: 42

# training

pl_trainer:
  fast_dev_run: True # Enable this for debug purposes
  gpus: 0
  precision: 32
#  max_steps: 500
  max_epochs: 1
  accumulate_grad_batches: 1
  num_sanity_val_steps: 1 # Set to -1 to check all validation data
  gradient_clip_val: 10.0
  log_every_n_steps: 10
  limit_train_batches: 0.02
  limit_val_batches: ${train.pl_trainer.limit_train_batches}

monitor_metric: 'valid/loss'
monitor_metric_mode: 'min'

early_stopping:
  patience: 42
  verbose: False

model_checkpoints:
  save_top_k: -1
  verbose: True

sample_visualisation: True
